### ISSUE TITLE
Ekran kichrayganda.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#1]
Ekran kichrayganda bu holat kuzatilmasligi uchun "logo" ga `..............` ni  "currency rates" ga   `..............` ni berib qo'ysangiz bunday bo'lmaydi. **{Harakat qilib ko'ring, agar topa lmasangiz, yordamlashaman}**
![image](https://user-images.githubusercontent.com/99461357/163285954-9f53956d-4a33-4e6f-84e5-bf8aba395436.png)

**Comment by NodirXon0609** [comment]
Hal qilindi.
