### ISSUE TITLE
Link ekanligi bilinsin.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#2]
Sayt foydalanuvchisi bu banner link ekanligini bilishi uchun bunga ikkilamchi stil bo'lsada `:hover` va `:active` holatlarini berib keting.
![image](https://user-images.githubusercontent.com/99461357/163286158-f238b92d-10f1-4f28-bba2-005e8ade25c9.png)

**Comment by NodirXon0609** [comment]
Bannerni hover va active holatlari berildi.
