### ISSUE TITLE
Agar `width:;` bilan ham tushmasa `br` bilan tushiring.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#3]
Sayt maket bilan bir xil-bo'lishi uchun ko'rsatilgan joydan so'ng `br` tagidan foydalaning.
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/163286501-361f05a9-f9d0-44b0-9668-397dfaacb404.png)

**Maketda**
![image](https://user-images.githubusercontent.com/99461357/163286698-b6dfd6e2-0e85-4cf3-96bd-04de924535dc.png)

**Comment by NodirXon0609** [comment]
Sarlavhalar maketdagi holat bilan bir xil bo'ldi.

**Comment by Muhammadjewel** [comment]
@MIRZOULUGBEK9008 , maketdagi bilan bir xil qilsakda sayt ishga tushganda boshqa ma'lumotlar keladi va matn joylashuvi o'zgarib ketadi. Shunga `<br>` shart emas.
