### ISSUE TITLE
`background-image:;` qani.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#4]
Rang ustidan `background-image:;`  beriladi.

**Sizda**
![image](https://user-images.githubusercontent.com/99461357/163286841-048d83f0-62d2-4446-b19c-4c30577d160c.png)

**Maketda**
![image](https://user-images.githubusercontent.com/99461357/163286963-df862aee-c37a-4370-9a57-07b44de2adee.png)

**Comment by NodirXon0609** [comment]
Rasm joylandi.
