### ISSUE TITLE
Ikkilamchi bo'lsada bu juda muhim.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#5]
![image](https://user-images.githubusercontent.com/99461357/163287078-c1fff1f3-4e17-478c-8a22-f01c88b44099.png)
`:hover`  va `:active` holatlari.

**Comment by NodirXon0609** [comment]
Ijtimoiy tarmoqlarni hover va active holatlari berildi.
