### ISSUE TITLE
html validator nimadir deyapti :)

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#7]
`section` ning o'rniga  `div` elementidan foydalaning (demoqda)
![image](https://user-images.githubusercontent.com/99461357/163287488-f4d1afda-6f8d-4eb8-8bb6-747a014fffb7.png)

**Comment by NodirXon0609** [comment]
h2 dan h6 gacha bo'lgan sarlavhalardan biridan foydalanishimni tavsiya qilyapdi.
