### ISSUE TITLE
Mijozda yaxshi ta'surot qoldiray desangiz.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [NodirXon0609/nmn-namanganliklar24#9]
**Aside** ushbu linkni ham boradigan joyi "index.html" bo'lmasligi kerak. Reallik muhim.
![image](https://user-images.githubusercontent.com/99461357/163288424-5d90a737-4bd9-46f0-a8e3-70adb5be7ee2.png)

Internetdan N24 ning Ijtimoiy tarmoqlari linklarini olishingiz mumkin. Shunda boradigan joyi "index.html" bo'lmaydi  :)
![image](https://user-images.githubusercontent.com/99461357/163288610-a26d78fc-0586-4769-8758-9a59c322ec90.png)

**Comment by NodirXon0609** [comment]
Reklamani bosish orqalik, https://olmosresidence.uz saytiga o'tib ketadigan qilindi.
Ijtimoiy tarmoqlarni bosish orqalik, namanganliklar24 saytini ijtimoiy tarmoqlardagi sahifalariga o'tib ketadigan qilindi.
